# Generated by Django 2.2.7 on 2019-12-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='describe',
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, default='input lyrics'),
        ),
    ]
