# Generated by Django 2.2.7 on 2019-12-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('author', models.CharField(default='Anonymous', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('describe', models.TextField(blank=True, default='Practice')),
            ],
        ),
    ]
